version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:9.11.2-stretch
    steps:
      - checkout
      - run:
          name: Download npm packages
          command: npm --prefix ./frontend install
      - run:
          name: Build production frontend
          command: npm --prefix ./frontend run build
      - run:
          name: Print built index
          command: cat ./frontend/dist/index.html
      - persist_to_workspace:
          root: ./
          paths:
            - ./frontend/dist
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-frontend
